apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: processing-l7
  namespace: platform
spec:
  endpointSelector:
    matchLabels:
      app: processing
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: hydration
      toPorts:
        - ports:
            - port: "50051"
              protocol: TCP
          rules:
            http:
              - method: "POST"
                path: "/processing.v1.ProcessingEngineService/.*"
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
      toPorts:
        - ports:
            - port: "50051"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app: prometheus
      toPorts:
        - ports:
            - port: "9090"
              protocol: TCP
          rules:
            http:
              - method: "GET"
                path: "/metrics"
    - fromEntities:
        - health
  egress:
    - toEndpoints:
        - matchLabels:
            app: redpanda
      toPorts:
        - ports:
            - port: "9092"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app: otel-collector
      toPorts:
        - ports:
            - port: "4317"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
