apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-test
  namespace: platform
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - platform
    labelSelectors:
      app: ingestion
  direction: both
  target:
    mode: all
    selector:
      namespaces:
        - platform
      labelSelectors:
        app: processing
  duration: "30s"
