apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-quality
  namespace: platform
  labels:
    app.kubernetes.io/name: data-quality
    app.kubernetes.io/component: data-quality
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: youtuop-platform
automountServiceAccountToken: false
