apiVersion: v1
kind: Service
metadata:
  name: ingestion-stable
  namespace: platform
  labels:
    app: ingestion
  annotations:
    # Topology Aware Routing — يوجّه الـ traffic لـ pods في نفس الـ AZ أولاً
    # يقلل cross-AZ latency وتكلفة الـ network
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  selector:
    app: ingestion
  ports:
    - name: grpc
      port: 8090
      targetPort: 8090
      protocol: TCP
    - name: http
      port: 9091
      targetPort: 9091
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-canary
  namespace: platform
  labels:
    app: ingestion
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  selector:
    app: ingestion
  ports:
    - name: grpc
      port: 8090
      targetPort: 8090
      protocol: TCP
    - name: http
      port: 9091
      targetPort: 9091
      protocol: TCP
  type: ClusterIP
