apiVersion: v1
kind: Service
metadata:
  name: notifications-stable
  namespace: platform
  labels:
    app: notifications
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  selector:
    app: notifications
  ports:
    - name: http
      port: 9094
      targetPort: 9094
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-canary
  namespace: platform
  labels:
    app: notifications
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  selector:
    app: notifications
  ports:
    - name: http
      port: 9094
      targetPort: 9094
      protocol: TCP
  type: ClusterIP
